name: Backend CI

on:
  push:
    branches: ["main", "dev"]
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  format:
    name: Format (ruff)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Format using ruff
        uses: dagger/dagger-for-github@v6.14.0
        with:
          version: "0.14.0"
          verb: call
          args: format --directory ./src

  lint:
    name: Lint (ruff)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Lint using ruff
        uses: dagger/dagger-for-github@v6.14.0
        with:
          version: "0.14.0"
          verb: call
          args: lint --directory ./src
