name: Backend CI

on:
  push:
    branches: ["main"]
    paths:
      - "backend/app/**"

jobs:
  format:
    name: Format (ruff)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Format using ruff
        uses: dagger/dagger-for-github@v6.14.0
        with:
          version: "0.13.7"
          verb: call
          args: format --directory ./backend/app

  lint:
    name: Lint (ruff)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Lint using ruff
        uses: dagger/dagger-for-github@v6.14.0
        with:
          version: "0.13.7"
          verb: call
          args: lint --directory ./backend/app
